apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

resources:
  - ../base

configMapGenerator:
  - name: haproxy-env-configmap
    behavior: merge
    envs:
      - dev.env

replicas:
  - name: haproxy
    count: 1
