apiVersion: v1
kind: Service
metadata:
  name: sbt-124
  labels:
    app: sbt-124
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 80
  selector:
    app: sbt-124
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbt-124
  labels:
    app: sbt-124
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sbt-124
  template:
    metadata:
      labels:
        app: sbt-124
    spec:
      containers:
        - name: sbt-124
          image: tutum/hello-world
