kind: ConfigMap
apiVersion: v1
metadata:
  name: rabbitmq-config-definitions
data:
  definitions.json: |
    {
      "vhosts": [{ "name": "/" }],
      "users": [
        {
          "name": "rabbitmq",
          "password": "rabbitmq",
          "tags": "administrator"
        }
      ],
      "permissions": [
        {
          "user": "rabbitmq",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [
        {
          "name": "cockroach-changefeed",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {
            "x-queue-type": "classic"
          }
        }
      ],
      "exchanges": [
        {
          "name": "cockroach-changefeed",
          "vhost": "/",
          "type": "direct",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "db-change",
          "vhost": "/",
          "type": "headers",
          "durable": true,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        },
        {
          "name": "presence",
          "vhost": "/",
          "type": "fanout",
          "durable": false,
          "auto_delete": false,
          "internal": false,
          "arguments": {}
        }
      ],
      "bindings": [
        {
          "source": "cockroach-changefeed",
          "vhost": "/",
          "destination": "cockroach-changefeed",
          "destination_type": "queue",
          "routing_key": "",
          "arguments": {}
        }
      ]
    }
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    management.load_definitions = /etc/rabbitmq/definitions.json
    default_user = rabbitmq
    default_pass = rabbitmq
---

