apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jhaynie/argocd2-test.git
          - list:
              elements:
                - url: https://kubernetes.default.svc
                  cluster: dev
  template:
    spec:
      source:
        repoURL: https://github.com/jhaynie/argocd2-test.git
