apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jhaynie/argocd2-test.git
              revision: HEAD
              files:
                - path: apps/*
          - list:
              elements:
                - cluster: dev
                  url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{path[0]}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/jhaynie/argocd2-test.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "{{url}}"
        namespace: "{{path[0]}}"
      syncPolicy:
        automated: {}
