apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jhaynie/argocd2-test.git
              revision: HEAD
              directories:
                - path: components/*
          - list:
              elements:
                - cluster: dev
                  url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: components
      source:
        repoURL: https://github.com/jhaynie/argocd2-test.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: "{{url}}"
        namespace: "default"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
