apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: deployments
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/jhaynie/argocd2-test.git
              revision: HEAD
              files:
                - path: deployments/*.json
          - list:
              elements:
                - cluster: dev
                  url: https://kubernetes.default.svc
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/jhaynie/argocd2-test.git
        targetRevision: HEAD
        path: "{{file}}"
      destination:
        server: "{{url}}"
        namespace: "{{namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
