apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
helmCharts:
  - name: minio
    repo: https://charts.min.io/
    releaseName: minio
    valuesInline:
      mode: standalone
      rootUser: minioroot
      rootPassword: minioroot
      replicas: 1
      persistence:
        size: 1Gi
      resources:
        requests:
          memory: 1Gi
      users:
        - accessKey: miniouser
          secretKey: miniouser
          policy: consoleAdmin
