apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/jhaynie/argocd2-test.git
    path: applicationsets/overlays/dev
