apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: haproxy

configMapGenerator:
  - envs:
      - base.env
    name: haproxy-env-configmap

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
