---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  labels:
    app: haproxy
spec:
  ports:
    - port: 5672
      protocol: TCP
      name: amqp
    - port: 26257
      protocol: TCP
      name: cockroach
    - port: 26999
      protocol: TCP
      name: stats
  selector:
    app: haproxy
