apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
spec:
  generators:
    - matrix:
        generators:
          - git:
              revision: HEAD
              files:
                - path: components/**/config.json
          - list:
              elements:
                - cluster: dev
  template:
    metadata:
      name: "{{deployment.name}}"
    spec:
      project: components
      source:
        targetRevision: HEAD
        path: "{{deployment.path}}"
      destination:
        server: "{{url}}"
        namespace: "{{deployment.namespace}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: "2s"
            factor: 2
            maxDuration: "10m0s"
