apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: components
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The Platform components we use for all applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
