apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployments
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The Application deployments we use for all applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
